/**
 * ============================================================================
 * Copyright (c) 2026 Verpitek, MB. All rights reserved.
 *
 * This code is proprietary and confidential. Unauthorized copying,
 * modification, distribution, or use of this material is strictly prohibited.
 *
 * Project: LunaTech Bedrock Add-On
 * ============================================================================
 */

import { ItemStack } from "@minecraft/server";

const VANILLA_COOK_TIMES: Record<string, number> = {
    "minecraft:bamboo": 50,
    "minecraft:scaffolding": 50,

    // Wool Carpets
    "minecraft:white_carpet": 67,
    "minecraft:light_gray_carpet": 67,
    "minecraft:gray_carpet": 67,
    "minecraft:black_carpet": 67,
    "minecraft:brown_carpet": 67,
    "minecraft:red_carpet": 67,
    "minecraft:orange_carpet": 67,
    "minecraft:yellow_carpet": 67,
    "minecraft:lime_carpet": 67,
    "minecraft:green_carpet": 67,
    "minecraft:cyan_carpet": 67,
    "minecraft:light_blue_carpet": 67,
    "minecraft:blue_carpet": 67,
    "minecraft:purple_carpet": 67,
    "minecraft:magenta_carpet": 67,
    "minecraft:pink_carpet": 67,

    // Overworld Buttons
    "minecraft:wooden_button": 100,
    "minecraft:acacia_button": 100,
    "minecraft:bamboo_button": 100,
    "minecraft:birch_button": 100,
    "minecraft:cherry_button": 100,
    "minecraft:dark_oak_button": 100,
    "minecraft:jungle_button": 100,
    "minecraft:mangrove_button": 100,
    "minecraft:pale_oak_button": 100,
    "minecraft:spruce_button": 100,

    // Overworld Saplings
    "minecraft:oak_sapling": 100,
    "minecraft:acacia_sapling": 100,
    "minecraft:birch_sapling": 100,
    "minecraft:cherry_sapling": 100,
    "minecraft:dark_oak_sapling": 100,
    "minecraft:jungle_sapling": 100,
    "minecraft:pale_oak_sapling": 100,
    "minecraft:spruce_sapling": 100,
    "minecraft:azalea": 100,
    "minecraft:flowering_azalea": 100,
    "minecraft:mangrove_propagule": 100,

    "minecraft:stick": 100,
    "minecraft:deadbush": 100,
    "minecraft:leaf_litter": 100,
    "minecraft:short_dry_grass": 100,
    "minecraft:tall_dry_grass": 100,

    // Wools
    "minecraft:white_wool": 100,
    "minecraft:light_gray_wool": 100,
    "minecraft:gray_wool": 100,
    "minecraft:black_wool": 100,
    "minecraft:brown_wool": 100,
    "minecraft:red_wool": 100,
    "minecraft:orange_wool": 100,
    "minecraft:yellow_wool": 100,
    "minecraft:lime_wool": 100,
    "minecraft:green_wool": 100,
    "minecraft:cyan_wool": 100,
    "minecraft:light_blue_wool": 100,
    "minecraft:blue_wool": 100,
    "minecraft:purple_wool": 100,
    "minecraft:magenta_wool": 100,
    "minecraft:pink_wool": 100,

    "minecraft:crossbow": 200,
    "minecraft:bow": 200,

    // Overworld Wooden Doors
    "minecraft:wooden_door": 200,
    "minecraft:acacia_door": 200,
    "minecraft:bamboo_door": 200,
    "minecraft:birch_door": 200,
    "minecraft:cherry_door": 200,
    "minecraft:dark_oak_door": 200,
    "minecraft:jungle_door": 200,
    "minecraft:mangrove_door": 200,
    "minecraft:pale_oak_door": 200,
    "minecraft:spruce_door": 200,

    // Overworld signs
    "minecraft:oak_sign": 200,
    "minecraft:acacia_sign": 200,
    "minecraft:bamboo_sign": 200,
    "minecraft:birch_sign": 200,
    "minecraft:cherry_sign": 200,
    "minecraft:dark_oak_sign": 200,
    "minecraft:jungle_sign": 200,
    "minecraft:mangrove_sign": 200,
    "minecraft:pale_oak_sign": 200,
    "minecraft:spruce_sign": 200,
    "minecraft:oak_hanging_sign": 200,
    "minecraft:acacia_hanging_sign": 200,
    "minecraft:bamboo_hanging_sign": 200,
    "minecraft:birch_hanging_sign": 200,
    "minecraft:cherry_hanging_sign": 200,
    "minecraft:dark_oak_hanging_sign": 200,
    "minecraft:jungle_hanging_sign": 200,
    "minecraft:mangrove_hanging_sign": 200,
    "minecraft:pale_oak_hanging_sign": 200,
    "minecraft:spruce_hanging_sign": 200,

    // Wooden Tools
    "minecraft:wooden_pickaxe": 200,
    "minecraft:wooden_shovel": 200,
    "minecraft:wooden_hoe": 200,
    "minecraft:wooden_axe": 200,
    "minecraft:wooden_sword": 200,

    "minecraft:bowl": 200,
    "minecraft:bamboo_mosaic": 300,
    "minecraft:bamboo_mosaic_slab": 300,
    "minecraft:bamboo_mosaic_stairs": 300,
    "minecraft:chiseled_bookshelf": 300,

    // Bamboo Blocks
    "minecraft:bamboo_block": 300,
    "minecraft:stripped_bamboo_block": 300,

    // Overworld Logs
    "minecraft:oak_log": 300,
    "minecraft:acacia_log": 300,
    "minecraft:birch_log": 300,
    "minecraft:cherry_log": 300,
    "minecraft:dark_oak_log": 300,
    "minecraft:jungle_log": 300,
    "minecraft:mangrove_log": 300,
    "minecraft:pale_oak_log": 300,
    "minecraft:spruce_log": 300,
    "minecraft:stripped_oak_log": 300,
    "minecraft:stripped_acacia_log": 300,
    "minecraft:stripped_birch_log": 300,
    "minecraft:stripped_cherry_log": 300,
    "minecraft:stripped_dark_oak_log": 300,
    "minecraft:stripped_jungle_log": 300,
    "minecraft:stripped_mangrove_log": 300,
    "minecraft:stripped_pale_oak_log": 300,
    "minecraft:stripped_spruce_log": 300,

    // Overworld Woods
    "minecraft:oak_wood": 300,
    "minecraft:acacia_wood": 300,
    "minecraft:birch_wood": 300,
    "minecraft:cherry_wood": 300,
    "minecraft:dark_oak_wood": 300,
    "minecraft:jungle_wood": 300,
    "minecraft:mangrove_wood": 300,
    "minecraft:pale_oak_wood": 300,
    "minecraft:spruce_wood": 300,
    "minecraft:stripped_oak_wood": 300,
    "minecraft:stripped_acacia_wood": 300,
    "minecraft:stripped_birch_wood": 300,
    "minecraft:stripped_cherry_wood": 300,
    "minecraft:stripped_dark_oak_wood": 300,
    "minecraft:stripped_jungle_wood": 300,
    "minecraft:stripped_mangrove_wood": 300,
    "minecraft:stripped_pale_oak_wood": 300,
    "minecraft:stripped_spruce_wood": 300,

    // Overworld Planks
    "minecraft:oak_planks": 300,
    "minecraft:acacia_planks": 300,
    "minecraft:bamboo_planks": 300,
    "minecraft:birch_planks": 300,
    "minecraft:cherry_planks": 300,
    "minecraft:dark_oak_planks": 300,
    "minecraft:jungle_planks": 300,
    "minecraft:mangrove_planks": 300,
    "minecraft:pale_oak_planks": 300,
    "minecraft:spruce_planks": 300,

    // Overworld Wooden Slabs
    "minecraft:oak_slab": 300,
    "minecraft:acacia_slab": 300,
    "minecraft:bamboo_slab": 300,
    "minecraft:birch_slab": 300,
    "minecraft:cherry_slab": 300,
    "minecraft:dark_oak_slab": 300,
    "minecraft:jungle_slab": 300,
    "minecraft:mangrove_slab": 300,
    "minecraft:pale_oak_slab": 300,
    "minecraft:spruce_slab": 300,

    // Overworld Wooden Stairs
    "minecraft:oak_stairs": 300,
    "minecraft:acacia_stairs": 300,
    "minecraft:bamboo_stairs": 300,
    "minecraft:birch_stairs": 300,
    "minecraft:cherry_stairs": 300,
    "minecraft:dark_oak_stairs": 300,
    "minecraft:jungle_stairs": 300,
    "minecraft:mangrove_stairs": 300,
    "minecraft:pale_oak_stairs": 300,
    "minecraft:spruce_stairs": 300,

    // Overworld Pressure Plates
    "minecraft:oak_pressure_plate": 300,
    "minecraft:acacia_pressure_plate": 300,
    "minecraft:bamboo_pressure_plate": 300,
    "minecraft:birch_pressure_plate": 300,
    "minecraft:cherry_pressure_plate": 300,
    "minecraft:dark_oak_pressure_plate": 300,
    "minecraft:jungle_pressure_plate": 300,
    "minecraft:mangrove_pressure_plate": 300,
    "minecraft:pale_oak_pressure_plate": 300,
    "minecraft:spruce_pressure_plate": 300,

    // Overworld Trap Doors
    "minecraft:trapdoor": 300,
    "minecraft:acacia_trapdoor": 300,
    "minecraft:bamboo_trapdoor": 300,
    "minecraft:birch_trapdoor": 300,
    "minecraft:cherry_trapdoor": 300,
    "minecraft:dark_oak_trapdoor": 300,
    "minecraft:jungle_trapdoor": 300,
    "minecraft:mangrove_trapdoor": 300,
    "minecraft:pale_oak_trapdoor": 300,
    "minecraft:spruce_trapdoor": 300,

    // Overworld Fence Gates
    "minecraft:fence_gate": 300,
    "minecraft:acacia_fence_gate": 300,
    "minecraft:bamboo_fence_gate": 300,
    "minecraft:birch_fence_gate": 300,
    "minecraft:cherry_fence_gate": 300,
    "minecraft:dark_oak_fence_gate": 300,
    "minecraft:jungle_fence_gate": 300,
    "minecraft:mangrove_fence_gate": 300,
    "minecraft:pale_oak_fence_gate": 300,
    "minecraft:spruce_fence_gate": 300,

    // Overworld Fence
    "minecraft:oak_fence": 300,
    "minecraft:acacia_fence": 300,
    "minecraft:bamboo_fence": 300,
    "minecraft:birch_fence": 300,
    "minecraft:cherry_fence": 300,
    "minecraft:dark_oak_fence": 300,
    "minecraft:jungle_fence": 300,
    "minecraft:mangrove_fence": 300,
    "minecraft:pale_oak_fence": 300,
    "minecraft:spruce_fence": 300,

    "minecraft:mangrove_roots": 300,
    "minecraft:ladder": 300,
    "minecraft:crafting_table": 300,
    "minecraft:cartography_table": 300,
    "minecraft:fletching_table": 300,
    "minecraft:smithing_table": 300,
    "minecraft:loom": 300,
    "minecraft:bookshelf": 300,
    "minecraft:lecturn": 300,
    "minecraft:composter": 300,
    "minecraft:chest": 300,
    "minecraft:trapped_chest": 300,
    "minecraft:barrel": 300,
    "minecraft:daylight_detector": 300,
    "minecraft:jukebox": 300,
    "minecraft:noteblock": 300,

    // Overworld Shelves
    "minecraft:oak_shelf": 300,
    "minecraft:acacia_shelf": 300,
    "minecraft:bamboo_shelf": 300,
    "minecraft:birch_shelf": 300,
    "minecraft:cherry_shelf": 300,
    "minecraft:dark_oak_shelf": 300,
    "minecraft:jungle_shelf": 300,
    "minecraft:mangrove_shelf": 300,
    "minecraft:pale_oak_shelf": 300,
    "minecraft:spruce_shelf": 300,

    "minecraft:banner": 300,
    "minecraft:fishing_rod": 300,

    // Overworld Boats
    "minecraft:oak_boat": 1200,
    "minecraft:acacia_boat": 1200,
    "minecraft:bamboo_raft": 1200,
    "minecraft:birch_boat": 1200,
    "minecraft:cherry_boat": 1200,
    "minecraft:dark_oak_boat": 1200,
    "minecraft:jungle_boat": 1200,
    "minecraft:mangrove_boat": 1200,
    "minecraft:pale_oak_boat": 1200,
    "minecraft:spruce_boat": 1200,
    "minecraft:oak_chest_boat": 1200,
    "minecraft:acacia_chest_boat": 1200,
    "minecraft:bamboo_chest_raft": 1200,
    "minecraft:birch_chest_boat": 1200,
    "minecraft:cherry_chest_boat": 1200,
    "minecraft:dark_oak_chest_boat": 1200,
    "minecraft:jungle_chest_boat": 1200,
    "minecraft:mangrove_chest_boat": 1200,
    "minecraft:pale_oak_chest_boat": 1200,
    "minecraft:spruce_chest_boat": 1200,

    "minecraft:coal": 1600,
    "minecraft:charcoal": 1600,

    "minecraft:blaze_rod": 2400,
    "minecraft:dried_kelp_block": 4000,
    "minecraft:coal_block": 16000,
}

export function tryGetCookTimeForItem(itemId: string) {
    return VANILLA_COOK_TIMES[itemId];
}